version: '3.9'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    platform: linux/amd64
    volumes:
      - python_bin:/usr/local/bin
      - python_lib:/usr/local/lib
      - python_include:/usr/local/include
      - python3.11:/usr/lib/python3.11
    command: tail -f /dev/null  # Keeps the container running

  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    platform: linux/amd64
    depends_on:
      - python
    volumes:
      - .:/tmp/openpilot
      - python_bin:/usr/local/bin
      - python_lib:/usr/local/lib
      - python_include:/usr/local/include
      - python3.11:/usr/lib/python3.11
    command: >
      bash -c "
        echo 'hello world' &&
        scons --cache-readonly -j$(nproc) > /dev/null
        # echo '/usr/local/lib' >> /etc/ld.so.conf.d/local.conf &&
        # ldconfig &&
      "

volumes:
  python_bin:
  python_lib:
  python_include:
  python3.11:

      # - usr_lib:/usr/lib:ro
      # - python_bin:/usr/local/bin:ro
      # - python_lib:/usr/local/lib:ro
      # - python_include:/usr/local/include:ro


      #       - python_bin:/usr/local/bin
      # - python_lib:/usr/local/lib
      # - python_include:/usr/local/include
      # - usr_lib:/usr/lib