FROM ubuntu:20.04

ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND=noninteractive

# Update and install necessary packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends sudo tzdata locales ssh pulseaudio xvfb x11-xserver-utils gnome-screenshot python3 python3-pip python3-venv git curl && \
    rm -rf /var/lib/apt/lists/* && \
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Add OpenCL and other dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils alien unzip tar xz-utils dbus gcc-arm-none-eabi tmux vim lsb-core libx11-6 && \
    rm -rf /var/lib/apt/lists/* && \
    dbus-uuidgen > /etc/machine-id

# Setup OpenCL
ARG INTEL_DRIVER=l_opencl_p_18.1.0.015.tgz
ARG INTEL_DRIVER_URL=https://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15532
RUN mkdir -p /tmp/opencl-driver-intel && \
    cd /tmp/opencl-driver-intel && \
    curl -O $INTEL_DRIVER_URL/$INTEL_DRIVER && \
    tar -xzf $INTEL_DRIVER && \
    for i in $(basename $INTEL_DRIVER .tgz)/rpm/*.rpm; do alien --to-deb $i; done && \
    dpkg -i *.deb && \
    mkdir -p /etc/OpenCL/vendors && \
    echo /opt/intel/opencl_compilers_and_libraries_18.1.0.015/linux/compiler/lib/intel64_lin/libintelocl.so > /etc/OpenCL/vendors/intel.icd && \
    cd / && \
    rm -rf /tmp/opencl-driver-intel

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENV QTWEBENGINE_DISABLE_SANDBOX 1

# Setup Python environment and install dependencies
RUN python3 -m venv /opt/venv && \
    chmod -R 755 /opt/venv && \
    /opt/venv/bin/pip install --upgrade pip poetry && \
    poetry config virtualenvs.create false

COPY tools/install_python_dependencies.sh /tmp/tools/
RUN chmod +x /tmp/tools/install_python_dependencies.sh && \
    set -x && cd /tmp && \
    ./tools/install_python_dependencies.sh /opt/venv && \
    rm -rf /tmp/*

# Global git configuration
RUN git config --global --add safe.directory /tmp/openpilot
