name: 'openpilot env setup'

inputs:
  docker_hub_pat:
    description: 'Auth token for Docker Hub, previously required for BuildJet jobs'
    required: false
    default: ''
  sleep_time:
    description: 'Time to sleep between retries'
    required: false
    default: '30'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Git LFS Pull
      run: git lfs pull
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y <list-of-packages>
      shell: bash

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Normalize file permissions
      run: |
        find . -type f -executable -not -perm 755 -exec chmod 755 {} \;
        find . -type f -not -executable -not -perm 644 -exec chmod 644 {} \;
      shell: bash
