name: 'openpilot env setup'

inputs:
  docker_hub_pat:
    description: 'Auth token for Docker Hub, previously required for BuildJet jobs'
    required: false
    default: ''
  sleep_time:
    description: 'Time to sleep between retries'
    required: false
    default: '30'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Git LFS Pull
      run: git lfs pull
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v3  
      with:
        python-version: '3.9'
        
    - name: Upgrade pip, setuptools, and wheel
      run: python -m pip install --upgrade pip setuptools wheel
      shell: bash

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y vim net-tools usbutils htop ripgrep tmux wget mesa-utils xvfb libxtst6 libxv1 libglu1-mesa libegl1-mesa
      shell: bash

    - name: Install Python dependencies
      run: |
        pip install ipython jupyter jupyterlab
      shell: bash

    - name: Install VirtualGL
      run: |
        curl -L -o virtualgl.deb "https://downloads.sourceforge.net/project/virtualgl/$(curl -s https://api.github.com/repos/VirtualGL/virtualgl/releases/latest | grep 'tag_name' | cut -d '"' -f 4)/virtualgl_$(curl -s https://api.github.com/repos/VirtualGL/virtualgl/releases/latest | grep 'tag_name' | cut -d '"' -f 4)_$(dpkg --print-architecture).deb"
        sudo dpkg -i virtualgl.deb
        rm virtualgl.deb
      shell: bash

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Normalize file permissions
      run: |
        find . -type f -executable -not -perm 755 -exec chmod 755 {} \;
        find . -type f -not -executable -not -perm 644 -exec chmod 644 {} \;
      shell: bash
