name: 'compile openpilot'

runs:
  using: "composite"
  steps:
    - shell: bash
    - name: Install with pip
      uses: insightsengineering/pip-action@v2
      with:
        packages: |
          scons
    - name: Build openpilot
      run: scons -j$(nproc)
      shell: bash
    - name: Check for dirty files
      run: bash release/check-dirty.sh
      shell: bash

    - name: Cleanup scons cache and rebuild
      run: |
          rm -rf /tmp/scons_cache/* && \
          scons -j$(nproc) --cache-populate
      shell: bash

    - name: Save scons cache
      uses: actions/cache/save@v3
      if: github.ref == 'refs/heads/master'
      with:
        path: .ci_cache/scons_cache
        key: scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
